apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --controller deployment
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: avant-website
  name: avant-website
  namespace: avant-test
spec:
  replicas: 1
<<<<<<< HEAD
  selector: 
    matchLabels:
      io.kompose.service: avant-website
=======
>>>>>>> b1416a6ad4dd9b5d56b92b7e73d60e1cbde2da9a
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --controller deployment
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: avant-website
    spec:
      containers:
      - env:
        - name: MAILSERVER_HOST
          value: avant-mailserver
        - name: MAILSERVER_PORT
          value: "2995"
        image: soren365/avant-web:1.0
        name: avant-website
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
