apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o helmcharts/avantweb/templates
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: avant-proxyserver
  name: avant-proxyserver
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
    nodePort: 31019
  selector:
    io.kompose.service: avant-proxyserver
  type: LoadBalancer
status:
  loadBalancer: {}
